---
title: "Literature Review"
format: pdf
editor: visual
bibliography: references.bib
---

## Identifying scale-emergent, nonlinear, asynchronous processes of wetland methane exchange

[@sturtevant2016]

Research Gaps:

-   Most challenging aspect of understanding ecosystem functioning is accounting for overlapping, asynchronous, nonlinear processes

-   Our ability to adequately model whole-ecosystem wetland methane emission is rudimentary [@bridgham2013], in part due to poorly resolved dynamics over a wide range of conditions at the whole-ecosystem level

-   Traditional statistical analysis often ignores scale and assumes linearity and synchronicity, limits the characterization of important dynamics

-   Combining wavelets and information theory to understand multiscale eco-atmosphere interactions is rare, only been applied to terrestrial upland sites

Objectives:

-   Research question: What do we miss by assuming linearity and/or synchronicity and ignoring scale-specific interactions?

-   1\) the dominant biosphere-atmosphere flux processes and time scales they act at; 2) their nonlinear and asynchronous characteristics and 3) how they contributed to the strength and timing of biosphere-atmosphere exchange.

The source's strengths and weaknesses:

Conclusions:

An evaluation of the research methodology:

1\) Wavelet Analysis

-   Wavelet decomposition characterizes both time scale and location of patterns and perturbations in the data

-   Maximal-overlap discrete wavelet transform [@percival1995],

2\) Information Theory

-   Mutual information [@fraser1986], I, describes the average tendency for paired states of two variables (X and Y) to coexist

-   Relative mutual information, Ir_xy = Ixy/Hy, represents the proportion of bits needed to represent Y that are superfluous given the knowledge of X (It's a normalized measure of statistical dependence of Y on X, higher values indicating greater dependence); the power of Ixy in the lack of parametric assumptions about the relationship between X and Y, thus able to identify linear and nonlinear interactions alike. By further adding temporal directionality in Ixy. torque = 0, "synchronous" interaction, variations in Y have the strongest dependence on concurrent variations in X; torque \< 0, variations in Y lead variations in X; torque \> 0, variations in Y lag variations in X;

Takeaways:

-   Methane emission in response to water table fluctuation can be nonlinear and lagged up to 10 days [@moore1993]

-   

## Heatwave effects on gross primary production of northern mid-latitude ecosystems

[@xu2020a; @xu2020]

Paper Type: Research data based (by using FLUXNET Tier-1 sites data)

Study sites: FLUXNET2015 Tier-1 sites

Statistical Analysis: Path Analysis (https://www.ibm.com/products/structural-equation-modeling-sem)

-   3 environmental variables, including sw radiation, Ta and ESI that can affect GPP directly; Ta/VPD/ESI and Rg may indirectly affect GPP by regulating Gc; biological element is closely related to GPP by directly regulating intracellular CO2; and Ta is linked with atmospheric transpiration demand (VPD) and ecosystem soil water condition (ESI)

Takeaways:

-   Impacts of heatwaves on ecosystem GPP varied by ecosystem type and plant functional type; GPP was depressed for most ecosystems during heatwaves while it was enhanced for C4 ecosystems

-   ESI was the primary variable for the discrepancy in GPP anomaly during heatwaves across the nine ecosystems

-   Decline in forest GPP induced by heatwaves was smaller than other ecosystems

Key Knowledge Points:

1\) C3/C4 ecosystems:

-   C3 Plants

    -   carbon fixation is the most common, which incorporate CO2 + RuBisCo -\> 3-phosphoglycerate

    -   All occured in mesophyll

    -   C3 Plants unfortunately have no special adaptations to avoid photorespiration; if the temperature rises above the ideal range (20-30 celsius degrees), C3 plants' photosynthesis rate falls dramatically.

-   C4 Plants

    -   close stomata to contain water loss; to avoid photo-respiration, CO2+PEP carboxylase -\> Oxaloacetate (4C) located in mesophyll cell, calvin cylcle occured in bundle sheath

    -   3% of land plants use this, ideal under 30-40 celsius degree

2\) Canopy conductance (Gc, canopy integrated stomatal conductance, mm/s):

-   a measure of water vapour transfer from the plant to the atmosphere. Conductance is the ease with which water can transfer from the plant to the atmosphere with higher values indicating easier transfer.

-   Aerodynamic conductance (mm/s), the ease with which air can move through a boundary layer,

3\) Evaporative Stress Index (ESI), representing standardized anomalies in the ratio of actual evapotranspiration (ET) to potential evapotranspiration (PET), has been extensively used to measure the degree of soil water stress for plants/ecosystems & minimize the impacts of non-moisture-related environmental drivers (eg. radiation and atmospheric demand) on ecosystem functions.

-   Negative ESI values -\> soil water supply is not sustained for ecosystem health

-   ET/PET; ET = latent heat flux (LE)/latent heat of vaporization (\~2.5 MJ/kg)

-   PET

-   ESI (timestep=w, year=y) = (V(w,y)-1/ny\*sum of V(w,y))/(standard deviation of V)

    -   V(w,y) -\> ratio of actual ET to potential ET for a given timestep (W) and year (y)

## Methane Emissions from Subtropical Wetlands: An Evaluation of the role of data filtering on annual methane budgets

[@staudhammer2022]

Paper Type: Theory,

Knowledge gaps:

-   CH~4~ fluxes, their range and controls are to a large extent not currently well understood, and thus robust methods for filtering and gap-filling data are generally lacking

-   many of these studies lack full-year temporal coverage, hinders our ability to develop annual methane budgets with confidence.

Objectives:

-   study the effects that data filtering has on gap-filled CH~4~ in these systems.

-   provide insight on how gaps in predictor variables for gap-filling models ---both their size and timing--- may affect the procedures used and subsequent annual budgets derived from CH~4~ data.

    -   compare between "unrestricted predictors model" (using all possible predictors regardless of gaps), versus a "restricted predictors model" (using gap-filled predictors or predictors with no missing values)

Key Knowledge Points:

-   Missing half hourly F~CO2~ data were gap filled using separate functions for day and night. When PAR was \>10 µmol m^−2^ s^−1^, F~CO2~ data were gap-filled using a Michaelis-Menten approach, and when PAR was ≤10 µmol m^−2^ s^−1^, F~CO2~ data were gap-filled using an Arrhenius approach.

-   

## Seasonal Patterns and Controls on Net Ecosystem CO2 Exchange in a Boreal Peatland Complex

Study Sites: Northern study area of boreal ecosystems atmosphere study (BOREAS)

Measurement method:

-   Clear chamber -\> NEE; Chamber, shrouds & different mesh sizes -\> develop relationship between NEE and PAR; CR10 and CR7 loggers -\> WT positions & peat Ts at different depths measured continuously

Takeaways:

-   Daily basis, ER:
    -   soil temperature at 5cm explains 43-74% of the variability in respiration
    -   Water table explains an additional 5-20% for ER
-   Seasonal basis:
    -   average seasonal dark CO2 flux is correlated strongly with average water table position for each collar location (However, the seasonal average water table position is an indication of the depth of the aerobic zone in the peat profile, which explains between-site differences better than average peat temperature)
-   Daily basis, GPP:
    -   PAR is the most important factor, explaining 39-58% of the variation
    -   average temperature & peat temperature: second most important factor, explaining an additional 8-16%
    -   water table position as the 3rd most important variable

## Estimating the carbon fluxes of forests with an individual-based forest model

[@rödig2017]

Paper Type: Model Testing

Objectives: used an individual-based forest gap model (FORMIND) that simulates the growth of individual trees by calculating its photosynthesis and respiration; soil carbon model

-   First, test whether the local forest model is generally capable of displaying daily carbon fluxes.

-   Second, analyzed whether the model processes correctly respond to variable climate inputs.

Take-away points:

Second, we analyzed whether the model processes correctly respond to variable climate inputs

Introduction:

-   correctly capturing the responses of an ecosystem to varying climatic conditions with vegetation models is a major challenge (Keenan et al. 2012).

## Terrestrial biosphere model performance for inter-annual variability of land-atmosphere CO2 Exchange

[@keenan2012]

## Europe-wide reduction in primary productivity caused by the heat and drought in 2003

Summary: Europe experienced a heatwave in 2003. Impacts of severe heatwaves on terrestrial carbon cycling is unclear. In this study, 1) used 14 forest sites' eddy data to analyse half-hourly GPP, TER, NEE, to assess the impact of extreme event on carbon balances, 2) used a terrestrial biosphere simulation model to estimate the continental-scale changes in primary productivity in 2003.

Before using the terrestrial biosphere model （ORCHIDEE biosphere model, [@krinner2005a]):

1\) Ran model at each EC site to verify its ability to reproduce the observed GPP and TER anomalies

## Identifying dominant environmental predictors of freshwater wetland methane fluxes across diurnal to seasonal time scales

[@knox2021]

Research Questions:

\(i\) What are the dominant predictors of FCH4 at diurnal to seasonal time scales at each wetland?

\(ii\) How does the relative dominance of each predictor vary across wetland types?

\(iii\) Is the identifi-cation of dominant predictors of FCH4 influenced by the choice of statistical approach?

\(iv\) How important are nonlinearities and lags in interpreting FCH4?

man-ual chamber measurements are typically discrete in time and space, and therefore may not capture the full spatiotemporal range of CH4dynamics, limiting the investigation of the underlying drivers and patterns of FCH4 in wetlands (Morin, 2019).

Pasoh Forest Reserve, Malaysia: http://asiaflux.net/index.php?page_id=93

## 

FLUXNET-CH~4~ SYNTHESIS ACTIVITY: Objectives, Observations, and Future Directions

While most of these sites measure CO2, water vapor, and energy exchange, the development of new and robust CH4 sensors has resulted in a rapidly growing number of CH4 EC measurements (Baldocchi 2014; Morin 2018), 

#### Increasing the number of tropical sites is particularly important for CH4 because more than half of global CH4 emissions are thought to come from this region (Saunois et al. 2016a; Dean et al. 2018). 

1\) Saunois, M., and Coauthors, 2016a: The global methane budget 2000--2012. *Earth Syst. Sci. Data*, **8**, 697--751, https://doi.org/10.5194/essd-8-697-2016.

(Latitudinal data from top-down emissions indicate a predominance of tropical emissions (∼ 64 % of the global budget, \< 30° N) as compared to mid (∼ 32 %, 30--60° N) and high northern latitudes (∼ 4 %, 60--90° N). )

2\) Dean, J. F., and Coauthors, 2018: Methane feedbacks to the global climate system in a warmer world. *Rev. Geophys.*, **56**, 207--250, https://doi.org/10.1002/2017RG000559.

(Of the total wetland CH~4~ emissions, tropical wetlands account for 50--60%, northern (Boreal and Arctic) wetlands \~34%, and temperate wetlands \~5% (Bloom et al., [2010](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2017RG000559#rog20161-bib-0036); Wanget al., [1996](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2017RG000559#rog20161-bib-0436)).)

Tropical Forests Methane:

Maludam, undisturbed swamp (MY-MLM): methane flux at a tropical peat forest in Sarawak, Malaysian Borneo. (1.454, 111.149)

# Why study methane?

1\) different conclusions regarding the drivers of the atmospheric CH4 growthrate over the past decades, making it difficult for national or regional policy makers to effectively implement strategies to control the sources of CH4 emissions. 2) Nearly two thirds of the global methane emissions of approximately 550 Tg CH4/year are thought to originate from tropical sources (Denman et al., 2007; Kirschke et al., 2013; Saunois, Bousquet, et al., 2016) and nearly one third from natural wetlands (Kirschke et al., 2013; Saunois, Bousquet, et al., 2016).

\
*(PDF) Eddy Covariance Measurements of Methane Flux at a Tropical Peat Forest in Sarawak, Malaysian Borneo*. Available from: <https://www.researchgate.net/publication/324618053_Eddy_Covariance_Measurements_of_Methane_Flux_at_a_Tropical_Peat_Forest_in_Sarawak_Malaysian_Borneo> \[accessed Oct 14 2023\].

## Accounting for the climate benefit of temporary carbon storage in nature

[@matthews2023]

## Peatlands in the Earth's 21st century climate system [@frolking2011]

Wetlands: Mineral wetlands and organic wetlands (peatlands)

Organic wetlands (peatlands): Fens - wetter peatlands that recieve water and nutrients from outside their own limits; Bogs - generally drier, nutrient poor systems primarily fed via atmosphere inputs.

Majority of peat (75-80%) is in boreal and sub-arctic peatlands; 10% - 15% in tropical peatlands, primarily in SE Asia, and maybe about 10% in temperate peatlands.

The net climate impact of current emissions has been assessed using the Global Warming Potential (GWP) methodology to classify an individual peatland as a net GHG source/sink based on net annual emission rates and a choice of time horizon. (Whiting and Chanton (2001) classified seven peatlands (sub-tropical to boreal) where they had measured CO2 and CH4 fluxes as net greenhouse gas (or CO2-equivalent) sources or sinks. For a 20-year time horizon, all seven sites were classified as net greenhouse gas sources; for a 500-year time horizon, all were classified as net sinks; and for a 100-year time horizon, the boreal sites were classified as sources, and the temperate and sub-tropical sites as sinks.)

Wetlands are and have been the dominant natural source of CH4 to the atmosphere.

The rise in atmospheric CH4 concentration between 1750 and 1990 has been attributed to the dramatic increase in anthropogenic emissions during that period (Denman et al. 2007). Since 1990, the growth rate of CH4 concentration in the atmosphere has slowed and become much more erratic (e. g., Dlugokencky et al. 2009).

**Peat vs. Forests**

peat C, unlike forest C, the redox boundary between oxia and anoxia, which can have a very strong influence on rates of CO2 and CH4 flux (Beer and Blodau 2007). Relatively small shifts in peatland hydrology will expose more or less peat to oxic conditions, enhancing or restricting decomposition,

**Fires**

In boreal and sub-arctic North America, peatlands experience a fire return interval of 75--300 years (Zoltai et al. 1998), with drier peatlands (bogs) experiencing more frequent fires and larger C losses than wetter peatlands (fens).

The net impacts of wildfire on peatland C emissions depends on post-fire response of hydrology and vegetation. (I think depends on vegetation recovery pattern and postfire effects of changing vegetation composition)

## Comparison of different chamber techniques for measuring soil CO2 efflux [@pumpanen2004]

The three major chamber technique on measuring soil CO2 fluxes:

Non-steady-state non-through-flow chamber (closed static chamber):

-   rising concentration in chamber could influence the efflux from soil by altering the natural soil concentration gradient

-   Pressure anomalies caused by

Non-steady-state through-flow chamber (closed dynamic chamber)

steady-state through flow chamber (open dynamic chamber

## Annual Greenhouse Gas Budget for a Bog Ecosystem undergoing Restoration by Rewetting

Small points:

-   Peatlands are the most widespread of all wetland types in the world, representing 50-70% of global wetlands

-   

## [@kettridge2015] Kettridge, N., Turetsky, M., Sherwood, J. *et al.* Moderate drop in water table increases peatland vulnerability to post-fire regime shift. *Sci Rep* 5, 8063 (2015). https://doi.org/10.1038/srep08063

Type of the research: a unique long-term experiment

Study site: A treed fen in Alberta, Canada

-   partially drained for silviculture (森林学) in 1983 -\> water table position was immediately lowered by 0.25m

-   The hydrological impact diminished over time as trenches used for drainage infilled, resulting in a 0.10 m difference in water table position between drained and undrained portions of the fen in 2003

-   In 2001, a 105,000 ha wildfire burned both the drained and undrained portions of the fen

Findings:

-   **We show that the moderate drop in water table position predicted for most northern regions triggers a shift in vegetation composition previously observed within only severely disturbed tropical peatlands**.

-   We observed the absence of *Sphagnum* moss cover at the drained site and a 77% reduction in total moss cover. This was concurrent with a lower maximum water table depth (drained 0.36 m; undrained 0.13 m) and higher maximum peat tension (drained 0.56 m; undrained 0.25 m) during the 2010 growing season. The drained site was instead colonized by a mature canopy of willow and birch.

Discussion:

-   A modification of the peatland hydrological function likely instigated the observed shift in vegetation recovery and associated carbon dynamics observed at this unique experimental site.
-   The transition to a deciduous canopy also provided additional leaf litter and low light transmissivities that have been shown to restrict the establishment of moss species, reinforcing the observed change from a peatland to a shrub ecosystem.

**Wildfire has been an important disturbance within the boreal region of North America throughout the Holocene** (Brandt, J. P., Flannigan, M. D., Maynard, D. G., Thompson, I. D. & Volney, W. J. A. An introduction to Canada's boreal zone: ecosystem processes, health, sustainability and environmental issues. Environ. Rev. 21, 207--226 (2013).)

## Plant community type is an indicator of the seasonal moisture deficit in a disturbed raised bog [**https://doi.org/10.1002/eco.2209**](https://doi.org/10.1002/eco.2209)

Purposes: 1) determine whether there's a relation between plant community type and a calculated moisture deficit related to residence time in a disturbed Burns Bog and 2) how WTMD (water moisture deficit) islinked to climate in Burns Bog, as well as how the relation variesamong different plant communities and as a function of proximity toditches and the bog's edge, historic disturbance and restorationactivities

67 study sites (4 study sites in the 2005 fire site & two in the 2016 fire site)

Source Text - Related to Fires:

**For example, in a 15-year study of a cutover and drained raised bog in northeast Germany, ditch block-ing resulted in a water level increase of approximately 45 cm after10 years; restoration of the water table resulted in a loss of trees and increase in Sphagnumcover (Bönsel & Sonneck, 2011)**

Fire can also impact the depth to water table and vegetation inpeatlands. Not only does fire burn surface vegetation, but any peatsituated above the water table may also burn, effectively lowering thesurface elevation and decreasing the depth to water table comparedto the prefire condition. The loss of the surface peat may result indenser and more humified (i.e., catotelmic) peat being exposed at thesurface (Sherwood et al., 2013), as well as near-surface water repel-lency due to the production of hydrophobic compounds (Mooreet al., 2017; Wilkinson, Verkaik, Moore, & Waddington, 2019). Firemay also increase nutrient supply in bogs (Depante et al., 2018). Dueto these effects, significant changes to bog vegetation can occur aftera fire, such as a reduction ofSphagnumcover and an increase in erica-ceous shrubs andCladoniaspecies (Damman, 1977).

(Assessing the moisture deficit using resi-dence time, in addition to measuring the depth to water table, has thepotential to allow peatland managers to track how longer, drier sum-mers affect moisture availability for plants)

## **Experimental warming increases ecosystem respiration by increasing above-ground respiration in alpine meadows of Western Himalaya**

<https://www.nature.com/articles/s41598-021-82065-y>

Stored SOC is released as atmospheric CO~2~ by soil respiration (SR). SR accounts for both autotrophic respiration by root and root-associated microbes and heterotrophic respiration by free-living soil microbes that decompose plant litter and stored SOC.

ER (contributed by above ground plant respiration and SR)

## On the temperature dependence of soil respiration (2024/01/06)

<https://www.jstor.org/stable/2389824?saml_data=eyJzYW1sVG9rZW4iOiJlYzQ5ODE4ZS05YjM1LTRlODEtYTAwOC1hMzY3YjQ2MWFiYTAiLCJpbnN0aXR1dGlvbklkcyI6WyIxMjJiMTFjOS00YWE5LTQzY2UtYWQzZS0xMmUyYTE4YmU3ZWUiXX0&seq=1>

## Partitioning of the net CO2exchange using an automated chamber system reveals plant phenology as key control of production and respiration fluxes in a boreal peatland (2024/01/07)

<https://onlinelibrary.wiley.com/doi/epdf/10.1111/gcb.14292>

## **Smouldering Fires and Natural Fuels (2024/01/08)**

[https://onlinelibrary.wiley.com/doi/epdf/10.1002/9781118529539.ch](https://onlinelibrary.wiley.com/doi/epdf/10.1002/9781118529539.ch2){.uri}2

@howie2020b investigated the relationship between plant community types and calculated moisture deficits across 67 BBECA study sites, revealing that lower water tables are associated with higher moisture deficits, leading to the absence of Sphagnum and the presence of taller shrubs and trees. Another 15-year study on examining changes in water level and vegetation in a restored German bog noted a comparable trend: increased water table levels resulted in reduced tree cover and enhanced Sphagnum growth [@bönsel2011b].

## Overriding Importance of water table in the greenhouse gas balance of managed peatlands

(<https://qmro.qmul.ac.uk/xmlui/bitstream/handle/123456789/78060/Heppell%20Overriding%20water%20table%202022%20Accepted.pdf;jsessionid=2DA2E43942518E03DB9E0818137AC12F?sequence=2>)

However, a range of previous studies have identified mean water-table depth (WTD) as an important influence on the emissions of all three major GHGs, with deeper water tables favouring CO2 and N2O emissions, and shallow water tables favouring CH4 emissions

(Tiemeyer, B. et al. High emissions of greenhouse gases from grasslands on peat and other
organic soils. Glob. Change Biol. 22, 4134--4149 (2016).; Couwenberg, J. et al. Assessing greenhouse gas emissions from peatlands using vegetation as a
proxy. Hydrobiologia 674, 67-89 (2011).)

Methods: Water-table depths were measured manually at all sites using PVC dipwells using a dip-meter, and then corrected to the distance from the peat surface (data were recorded as positive distance below the surface, with negative values indicating ponding above the peat surface).

At most sites a calibrated water-level sensor (pressure transducer) and integrated logger was also used to record water table depth in at least one dipwell, at a minimum one-hour frequency
