---
library()---
title: "Literature Review"
format: pdf
editor: visual
bibliography: references.bib
---

## Identifying scale-emergent, nonlinear, asynchronous processes of wetland methane exchange

[@sturtevant2016]

Research Gaps:

-   Most challenging aspect of understanding ecosystem functioning is accounting for overlapping, asynchronous, nonlinear processes

-   Our ability to adequately model whole-ecosystem wetland methane emission is rudimentary [@bridgham2013], in part due to poorly resolved dynamics over a wide range of conditions at the whole-ecosystem level

-   Traditional statistical analysis often ignores scale and assumes linearity and synchronicity, limits the characterization of important dynamics

-   Combining wavelets and information theory to understand multiscale eco-atmosphere interactions is rare, only been applied to terrestrial upland sites

Objectives:

-   Research question: What do we miss by assuming linearity and/or synchronicity and ignoring scale-specific interactions?

-   1\) the dominant biosphere-atmosphere flux processes and time scales they act at; 2) their nonlinear and asynchronous characteristics and 3) how they contributed to the strength and timing of biosphere-atmosphere exchange.

The source's strengths and weaknesses:

Conclusions:

An evaluation of the research methodology:

1\) Wavelet Analysis

-   Wavelet decomposition characterizes both time scale and location of patterns and perturbations in the data

-   Maximal-overlap discrete wavelet transform [@percival1995],

2\) Information Theory

-   Mutual information [@fraser1986], I, describes the average tendency for paired states of two variables (X and Y) to coexist

-   Relative mutual information, Ir_xy = Ixy/Hy, represents the proportion of bits needed to represent Y that are superfluous given the knowledge of X (It's a normalized measure of statistical dependence of Y on X, higher values indicating greater dependence); the power of Ixy in the lack of parametric assumptions about the relationship between X and Y, thus able to identify linear and nonlinear interactions alike. By further adding temporal directionality in Ixy. torque = 0, "synchronous" interaction, variations in Y have the strongest dependence on concurrent variations in X; torque \< 0, variations in Y lead variations in X; torque \> 0, variations in Y lag variations in X;

Takeaways:

-   Methane emission in response to water table fluctuation can be nonlinear and lagged up to 10 days [@moore1993]

-   

## Heatwave effects on gross primary production of northern mid-latitude ecosystems

[@xu2020a; @xu2020]

Paper Type: Research data based (by using FLUXNET Tier-1 sites data)

Abstract & Conclusion:

Key Knowledge Points:

1\) C3/C4 ecosystems:

-   C3 Plants

    -   carbon fixation is the most common, which incorporate CO2 + RuBisCo -\> 3-phosphoglycerate

    -   All occured in mesophyll

    -   C3 Plants unfortunately have no special adaptations to avoid photorespiration; if the temperature rises above the ideal range (20-30 celsius degrees), C3 plants' photosynthesis rate falls dramatically

-   C4 Plants

    -   close stomata to contain water loss; to avoid photo-respiration, CO2+PEP carboxylase -\> Oxaloacetate (4C) located in mesophyll cell, calvin cylcle occured in bundle sheath

    -   3% of land plants use this, ideal under 30-40 celsius degree

2\) Evaporative Stress Index (ESI):

-   Aerodynamic conductance (mm/s), the ease with which air can move through a boundary layer,
